### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by freever** [OneCyrus/GraphQL-AzureFunctions-HotChocolate#2]
Hi and thanks for putting out this sample. Have you had any success working with Variables, particularly passing in complex types as Variables? See this issue: https://github.com/ChilliCream/hotchocolate/issues/1342

**Comment by OneCyrus** [comment]
i added an example with the new HC parser: https://github.com/OneCyrus/GraphQL-AzureFunctions-HotChocolate/tree/feat_hcParser

check if this works for you.

**Comment by freever** [comment]
Thanks I am trying it out. At the moment I am getting an IOC error "Unable to resolve service for type 'HotChocolate.Language.IDocumentCache'"

I can't see it being registered anywhere in the sample, is it perhaps in a newer version of HC?

**Comment by OneCyrus** [comment]
it's registered with AddGraphQL()

it works fine here with the one in the branch (10.3.2)

![image](https://user-images.githubusercontent.com/7747800/72061442-2bf3a780-32d6-11ea-90a2-74174d721076.png)

**Comment by freever** [comment]
Thanks I registered it manually and it seems to work. 

Out of interest, do you recommend following the approach of registering the QueryExecutor the way you have it in this example (ie as a normal dependency) or the way I implemented it following an earlier sample which is to register it as a function binding and inject it into the function signature itself "[Inject(typeof(IQueryExecutor))] IQueryExecutor executor"?

**Comment by OneCyrus** [comment]
you mean like this? https://github.com/OneCyrus/GraphQL-AzureFunctions-HotChocolate/blob/ba31485345e503d04959a50ad95a521bf1748837/src/GraphQL.cs#L21

i wouldn't use it like that anymore. that was the way to go before AzF had support for dependency injection.

**Comment by freever** [comment]
OK thanks. Your solution works for me, thanks a mil!
